language: rust
sudo: required
services:
- docker
rust: stable
os:
  - linux
  - osx
matrix:
  allow_failures:
  - rust: nightly
  include:
  - os: linux
    rust: beta
  - os: linux
    rust: nightly
before_install:
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo apt-add-repository ppa:mc3man/trusty-media -y
    sudo apt-get -qq update
    sudo apt-get install -y ffmpeg
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
    brew install ffmpeg
  else
    echo "Don't know how to install ffmpeg"
    exit 1
  fi
script:
- cargo test --all
- |
  # Unset TRAVIS_TAG for everything but substudy itself, because that's the
  # only crate we want to actually deploy.
  if ! [[ "$TRAVIS_TAG" =~ ^substudy_.* ]]; then
    unset TRAVIS_TAG
  fi
before_deploy: "./build-release substudy ${TRAVIS_TAG}-${TRAVIS_OS_NAME}"
deploy:
  provider: releases
  api_key:
    secure: YvBa4SwOnI+XBZ//3lCQF9T3ZEQsZms2QhZXujuHmB1H/Znv37F0hrW3nVpVyiVxRV7FUNHZpBdZytblHdt03Zf/6pIooUZ/dr9pB/S8BajpAIQ+zlhYqHmg9MkfzAGw5LzVOdYcSTgK9k5/6UpSeZhHL0I/jsJnwKssPobFd0A=
  file: "substudy-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.*"
  file_glob: true
  skip_cleanup: true
  on:
    rust: stable
    tags: true
