[profile.dev]
# Enable this if you want to run `--ignored` tests against a large private
# corpus, or simply to improve performance in test mode.
#opt-level = 3

[workspace]
members = ["cli_test_dir", "vobsub", "vobsub2png", "opus_tools", "submodel", "subtitle_ocr", "subtitles2srt", "substudy", "backend"]
