[package]
name = "aligned_media"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]

[dependencies]
failure = "0.1.1"
isolang = { version = "0.2", features = ["serde_serialize"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
